variable "private_key_file" {}
variable "installer_ip" {}
variable "zone" {}
variable "domain" {}
variable "domain_ttl" {}
variable "node_count" {}
variable "node_size" {}
variable "node_disk" {}
variable "gluster_version" {}