#cloud-config

---
hostname: ${hostname}

package_upgrade: true
preserve_hostname: false
fqdn: ${hostname}.${domain}
runcmd:
  - systemctl stop firewalld
  - firewall-offline-cmd --add-service={http,https}
  - firewall-offline-cmd --add-port={10250,30000-32767,6783}/tcp
  - firewall-offline-cmd --add-port={8285,8472,6781-6784}/udp
  - systemctl start firewalld
